# Read about configuration here: https://jekyllrb.com/docs/configuration/options/
title: Client Diversity | Ethereum
description: Improve Ethereum's resilience and protect the network by using a minority client.
keywords: ethereum, client, diversity, eth, beacon, chain
url: https://clientdiversity.org
permalink: pretty # Do not change this, it will break all links
timezone: America/New_York
markdown: kramdown
livereload: true
# port: 4400


# Plugins
plugins:
  - jekyll-redirect-from # https://github.com/jekyll/jekyll-redirect-from
redirect_from: # jekyll-redirect-from
  json: false

# Global variables
analytics_tag: |
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-5YPSBBTM6W"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-5YPSBBTM6W');
  </script>
default_consensus_source: migalabs # Options: blockprint, migalabs, rated 
default_execution_source: supermajority # Options: ethernodes, supermajority

# Notification Bar
enable_notification: false
notification_msg_id: 1 # must increment when creating a new message
notification_msg: Join the community! <br><a href=""></a>.
notification_expiration: 3000000000 # epoch time in seconds

# Toast
enable_toast: true
toast_msg_id: 5 # must increment when creating a new message
toast_title: Ether Alpha's Gitcoin grant is live!
toast_msg: This round runs until November 30th. If you enjoy this or <a href='https://etheralpha.org/' target='_blank'>other tools</a> created, please support to help maintain existing projects and fund new ones. # Best when under 200 characters
toast_link: https://explorer.gitcoin.co/#/round/424/0xd4cc0dd193c7dc1d665ae244ce12d7fab337a008/0xd4cc0dd193c7dc1d665ae244ce12d7fab337a008-20 # Optional, leave blank to omit
toast_link_text: Donate
# August 29rd, 12:00:00 GMT+0
toast_expiration: 1701302399 # epoch time in seconds

# Navigation
nav_enabled: true

# Links
github_repo: https://github.com/etheralpha/clientdiversity-org

